Support plugin_name in ember cfg
Add support for using X_CSI_EMBER_CSI's project_id to identify the
instance of driver

Use spaces vs tab for the new commit

Add support for plugin_name which identifies unique instances of the
driver

Add Travis CI jobs

This patch adds 2 jobs:

- PEP8 checks
- Unit tests

We only have a trivial unit test, but now that we have a job, whenever
we start adding tests they will run automatically.

Examples: Fix removed iscsi parameters

On Cinder's Queens release iscsi_helper and iscsi_protocol parameters
were removed, update the baremetal examples to use target_protocol and
target_helper parameters instead.

Fix list index out of range

When we receive a request with a node_id that is not present in the
persistence storage we raise an Exception in Ember-CSI:

    File "/usr/lib/python2.7/site-packages/ember_csi/ember_csi.py",
     line 236, in get
      return cls(node_id, json.loads(kv[0].value))
  IndexError: list index out of range

After this patch we will return a NOT_FOUND error instead.

Fail on incompatible readonly modes

We now fail when trying to attach on readonly mode a SINGLE_NODE_WRITE
access type volume, and when trying to attach a non readonly volume on
with SINGLE_NODE_READER_ONLY.

Add LVM CI job

This patch adds LVM CI jobs using csi-sanity.

It also changes how we build our images. Now we only push a new image to
Docker Hub if the tests pass successfully.  And we only bother to build
the images if PEP8, Unit tests, and LVM jobs run successfully.

Fix LVM latests CI job

We were not running with the right repositories.  This patch fixes it
and we now use cinder@stable/rocky and cinderlib master to test the
"latest".

[skip ci]

Sync with Akrog/master

Add support for plugin_name, which will be used to spawn multiple driver instances

Update required PR fixes

Fix indentation to appease PEP8

Fix indentation to appease PEP8

Use raw strings in regex match

Add string check before validating regex

Remove debugging stmt