Fix #77: ValueError volume_content_source
We could not create volumes from snapshots, as we would get the
following error on the CSI plugin:

ValueError: Protocol message Volume has no "volume_content_source"
field.

We were using "volume_content_source" instead of "content_source" when
returning the created volume information, fix it.